### ISSUE TITLE
News on this package

### ISSUE THREAD

**Issue by ValATG** [tthmatt/Omron_LD_ROS_Package#2]
Hello,

I'm a robotic engineer and I'm working on a MoMa (Mobile Manipulator) with a LD-250 and a TM-12.
I would like to know if somebody still working on this ROS package ? Did you worked on a MoMa ?
I've tried this package with an LD-60 and it works perfectly. It will help me a lot in the future.

Best regards,

**Comment by zach-goh** [comment]
Hi there.  We are not currently working on this ROS package but may do so in the near future.  We use MoMa too but will leverage Techman's official ROS package for controlling the arm.  But we have not integrated these 2 packages and test them yet.  May I know which Omron country office you bought your robots from?  And is your company's name "ValATG"?

**Comment by ValATG** [comment]
Hi,
Yes I'm going to use the TM official ROS package too.
I've made an URDF for the LD-250. It could be interesting for you.
We're buying our robot from Omron France office. My company is ATG Technologies, based in Avignon, France.
You can contact me by email, Whatsapp or Teams if you want.
Best regards

**Comment by zach-goh** [comment]
Thank you for the information.  I'm sure your LD250-TM12 MoMa will perform amazingly once the ROS development is complete.  It will be great if you can share your URDF for the LD250 so we can reuse.  I will contact you separately by email.  Have a merry Christmas and a fantastic new year!
