### ISSUE TITLE
Extracting map data from Omron EM Fleet Manager

### ISSUE THREAD

**Issue by rllyryan** [tthmatt/Omron_LD_ROS_Package#5]
Hi!

I am currently doing a project that extracts map data from different fleet managers, and merge them into one universal map for end users to view. This is somewhat different from map merging tools that focus on one fleet manager. 

Could I ask what kind of map data can be extracted from the fleet manager for OMRON?

If yes, is it similar to that of the file type produced by the ROS package 'map_server' under the navigation stack?

If no, how else are we able to extract map information from the robot?

I have had experience operating the robot via self-made TCP/IP socket scripts to send commands to the LD robot. 

Thank you for your time!

**Comment by zach-goh** [comment]
You cannot extract the map directly.  One way that may achieve this is to query the fleet manager via ARCL (TCP/IP sockets) to get all the map objects separately like walls, goals, forbidden areas etc.   Commands like "mapObjectList" may work.  But I don't know whether such commands provide enough information to get the map that you need.  If you have a robot with you, you can try it out.

**Comment by rllyryan** [comment]
Thank you for your reply!

Another thing, does OMRON have a specific document for the fleet manager that I can refer to? (For interfacing and connecting to, for understanding how the FM works, extraction of information from it, and etc.) --> Is this already provided in this gituhub repository?

**Comment by zach-goh** [comment]
Which fleet manager do you have?  The EM2100 documentation is online https://assets.omron.eu/downloads/manual/en/v5/i631_enterprise_manager_2100_users_manual_en.pdf
Interfacing via APIs is via ITK and documented here https://assets.omron.eu/downloads/manual/en/v3/i637_fleet_operation_workspace_core_integration_toolkit_users_manual_en.pdf

**Comment by rllyryan** [comment]
Hi Zach,

Thank your for the documents you have provided!

Do you also have the ARCL booklet for the EM Fleet Manager too?

Also, I was thinking since Omron is able to operate under ROS (not certain to the extent in which it is supported), will it be possible for the Omron robot to execute Gmapping and produce a map that is extractable (pgm and .yaml)?

**Comment by zach-goh** [comment]
The ARCL documentation can be found through a simple google search.  But not all ARCL commands work with the Fleet manager if you read the document carefully.  As you cannot read the robot's wheel encoder values through ARCL, you cannot create a map using ROS like in the way you described.
